In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import GradientBoostingRegressor
import category_encoders as ce
from sklearn.pipeline import make_pipeline

In [10]:
df = pd.read_csv('../data/master.csv', parse_dates=['visit_date'])

In [11]:
df = df.fillna(0)

In [12]:
df.drop(['calendar_date', 'visit_date'], axis=1, inplace=True)

In [13]:
df

id  visitors day_of_week  holiday           genre  \
0       air_ba937bf13d40fb24        25   Wednesday        0      Dining bar   
1       air_ba937bf13d40fb24        32    Thursday        0      Dining bar   
2       air_ba937bf13d40fb24        29      Friday        0      Dining bar   
3       air_ba937bf13d40fb24        22    Saturday        0      Dining bar   
4       air_ba937bf13d40fb24         6      Monday        0      Dining bar   
...                      ...       ...         ...      ...             ...   
252103  air_a17f0778617c76e2        49      Friday        0  Italian/French   
252104  air_a17f0778617c76e2        60    Saturday        0  Italian/French   
252105  air_a17f0778617c76e2        69      Sunday        0  Italian/French   
252106  air_a17f0778617c76e2        31      Monday        1  Italian/French   
252107  air_a17f0778617c76e2        26      Sunday        0  Italian/French   

                                area   latitude   longitude  reserve_visitors  
0       Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599               0.0  
1       Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599               0.0  
2       Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599               0.0  
3       Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599               0.0  
4       Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599               0.0  
...                              ...        ...         ...               ...  
252103  Hyōgo-ken Kōbe-shi Kumoidōri  34.695124  135.197852               6.0  
252104  Hyōgo-ken Kōbe-shi Kumoidōri  34.695124  135.197852              37.0  
252105  Hyōgo-ken Kōbe-shi Kumoidōri  34.695124  135.197852              35.0  
252106  Hyōgo-ken Kōbe-shi Kumoidōri  34.695124  135.197852               3.0  
252107  Hyōgo-ken Kōbe-shi Kumoidōri  34.695124  135.197852              32.0  

[252108 rows x 9 columns]

In [16]:
def create_val_splits(df, val_units=15, return_val=False):
    """Function that will take in a dataset and split it up into training, validation, and test sets"""
    # split into training, validation, and test sets
    #df = df.drop('visit_date', axis=1)
    train = df.groupby('id').apply(lambda x: x.iloc[:-val_units]).reset_index(drop=True)
    test  = df.groupby('id').apply(lambda x: x.iloc[-val_units:]).reset_index(drop=True)
    
    if return_val:
        val   = train.groupby('id').apply(lambda x: x.iloc[-val_units:]).reset_index(drop=True)
        train = train.groupby('id').apply(lambda x: x.iloc[:-val_units]).reset_index(drop=True)
        return train, val, test
    else:
        return train, test

In [17]:
train, test = create_val_splits(df)

In [18]:
X_train, y_train = train.drop('visitors', axis=1), train['visitors']

In [19]:
from sklearn.model_selection import cross_val_score, KFold, TimeSeriesSplit

In [20]:
splitter = KFold(n_splits=5)
splitter2 = TimeSeriesSplit(n_splits=5)

In [21]:
te = ce.TargetEncoder(min_samples_leaf = 30)
mod = GradientBoostingRegressor()

pipe = make_pipeline(te, mod)

In [22]:
scores = cross_val_score(pipe, X=X_train, y=y_train, cv=splitter2)

C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders

In [23]:
scores

array([0.05659875, 0.06234163, 0.04232528, 0.02566006, 0.04471928])

In [24]:
scores.mean()

0.04632900095708357

In [25]:
scores

array([0.05659875, 0.06234163, 0.04232528, 0.02566006, 0.04471928])

In [27]:
import xgboost as xgb

In [31]:
df = pd.read_csv(r"https://raw.githubusercontent.com/JonathanBechtel/dat-02-22/main/ClassMaterial/Unit3/data/ks2.csv")

In [34]:
df['state'].unique()

array([0, 1], dtype=int64)

In [35]:
def split_data(df, split_frac=0.2, return_val=False, random_state=42):
    df = df.drop(['deadline', 'launched'], axis = 1)
    X  = df.drop('state', axis=1)
    y  = df['state']
    return train_test_split(X, y, test_size = split_frac, stratify = y, random_state = random_state)

In [37]:
def get_model_scores(mod, X_train, y_train, X_test, y_test, val_score = True, test_score=False):
    if val_score:
        X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, 
                                                          test_size = 0.2, 
                                                          stratify = y_train, 
                                                          random_state= 42)
 
    mod.fit(X_train, y_train)
    
    results = {}
    
    results['train_score'] = mod.score(X_train, y_train)
    if val_score:
        results['val_score'] = mod.score(X_val, y_val)
        
    if test_score:
        results['test_score'] = mod.score(X_test, y_test)
        
    return results

In [38]:
from sklearn.ensemble import GradientBoostingClassifier

In [41]:
from sklearn.model_selection import train_test_split

In [39]:
te = ce.TargetEncoder(min_samples_leaf = 30)
mod = xgb.XGBClassifier()

pipe = make_pipeline(te, mod)

In [42]:
X_train, X_test, y_train, y_test = split_data(df)

In [48]:
y_test

32126     0
116502    1
329951    0
141800    1
333423    1
         ..
198806    1
184675    1
62207     0
127842    0
328744    1
Name: state, Length: 74091, dtype: int64

In [49]:
scores = get_model_scores(pipe, X_train, y_train, X_test, y_test, test_score = True)

C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
C:\Users\Jonat\AppData\Roaming\Python\Python38\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[23:09:48] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
