In [1]:
import numpy as np

In [3]:
var = np.arange(20).reshape(5, 4)

In [4]:
var

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [5]:
var

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [6]:
var.mean()

9.5

In [7]:
var.mean(axis=0)

array([ 8.,  9., 10., 11.])

In [8]:
var.mean(axis=1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5])

In [9]:
import pandas as pd

In [11]:
df = pd.read_csv(r"C:\Users\Jonat\dat-07-26\ClassMaterial\Unit2\data\restaurant_data\master.csv")

`Option` + `Command` + `C`

In [12]:
df

id  visit_date  visitors calendar_date day_of_week  \
0       air_ba937bf13d40fb24  2016-01-13        25    2016-01-13   Wednesday   
1       air_ba937bf13d40fb24  2016-01-14        32    2016-01-14    Thursday   
2       air_ba937bf13d40fb24  2016-01-15        29    2016-01-15      Friday   
3       air_ba937bf13d40fb24  2016-01-16        22    2016-01-16    Saturday   
4       air_ba937bf13d40fb24  2016-01-18         6    2016-01-18      Monday   
...                      ...         ...       ...           ...         ...   
252103  air_a17f0778617c76e2  2017-04-21        49    2017-04-21      Friday   
252104  air_a17f0778617c76e2  2017-04-22        60    2017-04-22    Saturday   
252105  air_a17f0778617c76e2  2017-03-26        69    2017-03-26      Sunday   
252106  air_a17f0778617c76e2  2017-03-20        31    2017-03-20      Monday   
252107  air_a17f0778617c76e2  2017-04-09        26    2017-04-09      Sunday   

        holiday           genre                          area   latitude  \
0             0      Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068   
1             0      Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068   
2             0      Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068   
3             0      Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068   
4             0      Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068   
...         ...             ...                           ...        ...   
252103        0  Italian/French  Hyōgo-ken Kōbe-shi Kumoidōri  34.695124   
252104        0  Italian/French  Hyōgo-ken Kōbe-shi Kumoidōri  34.695124   
252105        0  Italian/French  Hyōgo-ken Kōbe-shi Kumoidōri  34.695124   
252106        1  Italian/French  Hyōgo-ken Kōbe-shi Kumoidōri  34.695124   
252107        0  Italian/French  Hyōgo-ken Kōbe-shi Kumoidōri  34.695124   

         longitude  reserve_visitors  
0       139.751599               NaN  
1       139.751599               NaN  
2       139.751599               NaN  
3       139.751599               NaN  
4       139.751599               NaN  
...            ...               ...  
252103  135.197852               6.0  
252104  135.197852              37.0  
252105  135.197852              35.0  
252106  135.197852               3.0  
252107  135.197852              32.0  

[252108 rows x 11 columns]